// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akznvrkofmtgmuueyvev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrem52cmtvZm10Z211dWV5dmV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NjA5ODcsImV4cCI6MjA2MTUzNjk4N30.mcvtMW0Kb36z8YR6ufVsZElCyHVTUm4QxxIQSfpZ8TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);